Fix KenLM model generation on smaller texts
mozilla/DSAlign pull request #18
Opened 2020-01-22 09:00 UTC by lunixbochs

Add --discount-fallback argument to lmplz, which was necessary when generating a language model for a smaller transcription. This option enables a fallback, and shouldn't affect anything except KenLM models that would've otherwise errored out.

2020-01-22 09:03 UTC, lunixbochs commented
Before this flag, I had to use `--stt-no-own-lm`, which had much worse hit rate on my data:
```
INFO:root:Aligned 44 fragments
INFO:root:Dropped 50 fragments 113.64%:
INFO:root: - character error rate (CER) too high: 32
```

Versus using an LM with the flag:
```
INFO:root:Aligned 66 fragments
INFO:root:Dropped 28 fragments 42.42%:
INFO:root: - character error rate (CER) too high: 12
```

2020-01-31 10:59 UTC, tilmankamp requested changes
How about adding a CLI parameter for turning this on? Always using it could result in lower quality for bigger texts.

2020-01-31 15:16 UTC, lunixbochs commented
Again, it only applies _if the error would occur_, which (1) should never happen on a large enough text (2) if it happens, DSAlign just breaks anyway

2020-01-31 15:23 UTC, tilmankamp commented
You convinced me. Thanks for looking this up!

2020-01-31 15:24 UTC, merged